server:
  port: 8081

spring:
  devtools:
    restart:
      exclude: static/**,templates/**
  thymeleaf:
    cache: false
#  mvc:
#    dispatch-trace-request: true
#    dispatch-options-request: true